#!/bin/sh

set -e

#DEBHELPER#

PLUGINS=lilo

if [ "$2" ] && dpkg --compare-versions $2 '<' 0.2.0-2
then
    for plugin in $PLUGINS
    do
        if [ -e /etc/sjconf-lilo/templates/$plugin ] ; then
            sjconf --uninstall-template $plugin || true
        fi
        sjconf --uninstall-conf $plugin || true
        sjconf --uninstall-plugin $plugin || true
        # dpkg will preserve these files but it should not in this case
        rm -r /etc/sjconf-lilo/ || true
    done
fi
